# Generated by Django 5.0.6 on 2024-10-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=100, unique=True)),
                ('gift_text', models.TextField(blank=True, null=True)),
                ('gift_link', models.URLField(blank=True, null=True)),
                ('gift_image', models.ImageField(blank=True, null=True, upload_to='gift_images/')),
            ],
        ),
    ]
