# Generated by Django 5.0.6 on 2024-10-18 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_alter_gift_link_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='link_name',
            new_name='user',
        ),
    ]
