# Generated by Django 5.0.6 on 2024-10-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0003_rename_link_name_gift_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='user',
        ),
        migrations.AddField(
            model_name='gift',
            name='link_name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
