# Generated by Django 5.0.6 on 2024-10-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0004_remove_gift_user_gift_link_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='link_name',
            field=models.CharField(max_length=100),
        ),
    ]
