# Generated by Django 5.0.6 on 2024-10-22 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0006_remove_gift_gift_image_remove_gift_gift_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='gift_image',
            field=models.ImageField(blank=True, null=True, upload_to='gift_images/'),
        ),
        migrations.AddField(
            model_name='gift',
            name='gift_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='GiftItem',
        ),
    ]
